### ISSUE TITLE
Why Does Test-Client-Web Have Target Selector?

### ISSUE THREAD

**Issue by martinpeck** [microsoft/aoai-api-simulator#30]
The `test-client-web` has a target selector in the UI:

![image](https://github.com/user-attachments/assets/4a18260b-3abe-4e14-9bd6-504ac2bb1ae5)

And the following code supports this:

https://github.com/microsoft/aoai-api-simulator/blob/693fa891923e04b79a0a69b758ecd271a48879ee/tools/test-client-web/app.py#L38-L53

However, there are some problems with this code:

1. It hard-codes where the simulator lives (specifically, it assumes `localhost`). What if I've deployed the simulator to ACA, or I'm running it locally on a different port.
2. In situations where I only have the simulator running (locally, or otherwise), it requires me to specify some env vars that I would otherwise not need

Is this target switching required?

Why doesn't the `test-client-web` simply run against whatever the configured endpoints are? i.e. do the same thing as the `test-client`?

My suggestion is that we remove this target selector, change the code to always use the env vars, and have this client do the same thing as the `test-client`.

@stuartleeks: what do you think?

**Comment by stuartleeks** [comment]
I can't fully remember why the switcher is there! So I reckon probably remove it and just keep the simulator flow.

> Why doesn't the test-client-web simply run against whatever the configured endpoints are? i.e. do the same thing as the test-client?
Yes, I agree - let's go with that approach 👍

**Comment by martinpeck** [comment]
I'm going to open another issue related to environment variables and, as part of resolving that issue, I'll strip out the selector code from the test-client-web project.

**Comment by martinpeck** [comment]
I've opened #34 to track the work related to this, and feel this question can now be closed.
