### ISSUE TITLE
Fix flaky test_generation_min_max_time_10_000_tokens test

### ISSUE THREAD

**Issue by stuartleeks** [microsoft/aoai-api-simulator#33]
The `test_lorem_generation.py::test_generation_min_max_time_10_000_tokens` test is occasionally failing, see [this example](https://github.com/microsoft/aoai-api-simulator/actions/runs/10721729918/job/29730940588?pr=32#step:3:4232)

Two thoughts on this:
1. we should probably set the threshold to 9993 for this test as all failures have had that value (and it's good enough)
2. we should have messages for failed assertions so that they're easier to interpret in the output

**Comment by martinpeck** [comment]
Grabbing this issue.
